### ISSUE TITLE
JSON-L

### ISSUE THREAD

**Issue by jpmckinney** [ndjson/ndjson-spec#23]
https://tools.ietf.org/html/draft-hallambaker-jsonl-01

Proposes media type `application/json-l` and extension `.jsonl`. In use by Canadian government, for example.

Is ndjson different in any important respect? If not, it may make sense to pursue NDJSON as an IETF RFC.

**Comment by finnp** [comment]
Thank you for this link. Yes there are some important differences right now. Like this spec only allows JSON objects `{}` and not any kind of JSON. Also it allows for multiple new lines and whitespaces between the objects. 

Those are subtle differences, because in 99% of the cases it will probably be compatible. But no, right now it is not the same.

**Comment by jpmckinney** [comment]
According to RFC7159:

    JSON-text = ws value ws

And:

    Insignificant whitespace is allowed before or after any of the six structural characters.

Insignificant whitespace (`ws`) being Space, Horizontal tab, Line feed/New line, Carriage return. The six structural characters being `[ ] { } : ,`.

So, NDJSON, as written, allows multiple newlines and whitespaces between objects, if "JSON text" in the NDJSON spec means the same thing as "JSON text" in the RFC.

So, the only difference is that NDJSON allows each line to be any JSON, not just a JSON object.

**Comment by finnp** [comment]
The current spec says
```
 The JSON texts MUST NOT contain newlines or carriage returns.
```

So yes whitespaces is allowed, but not multiple newlines as in JSON-L.

**Comment by VladimirAlexiev** [comment]
@finnp I think this means that newlines in strings are not allowed. But insignificant whitespace is allowed

**Comment by jpmckinney** [comment]
Newlines in strings are never allowed in JSON - they need to be escaped `\n`. "The JSON texts MUST NOT contain newlines or carriage returns." means that the full JSON text must be on a single line.
