### ISSUE TITLE
Is ndjson file support comment / remark

### ISSUE THREAD

**Issue by jasper2virtual** [ndjson/ndjson-spec#30]
sometime we may need to skip some data temporary. can ndjson file be comment line by line. 
for example , 
{"data":"one","visible":true}
// skip me {"data":"two","visible":false}
{"data":"three","visible":true}

**Comment by bradisbell** [comment]
This isn't supported by JSON, and therefore should not be supported in ND-JSON, in my opinion.

**Comment by danm** [comment]
Also agree.  Maybe speak to the JSON5 group about a NDJSON5 ?

**Comment by olibre** [comment]
One way to manage comments in JSON, is to use a key `"comment"` (you may use another key name).

```json
{"data":"one","visible":true}
{"comment":{"data":"two","visible":false},"msg":"skip me"}
{"data":"three","visible":true}
```
