### ISSUE TITLE
Expressing trees

### ISSUE THREAD

**Issue by AndyOGo** [ndjson/ndjson-spec#31]
I really like this idea, it's perfect for lists or arrays.

Though I wonder how would one represent trees?
Nested or recursive data introduces a parent/child relationship 🤔

**Comment by kassio** [comment]
I'm new here too, but I believe you could do that using a file tree instead of trees inside the file. Like:
```console
/
|- projects.ndjson
|- projects/
   |- project1.ndjson
   |- project2.ndjson
# ...
```

**Comment by michaelcoxon** [comment]
@AndyOGo My guess is that you would need to do a deep merge of some-sort and have a key that can get the data in order.
