### ISSUE TITLE
https://github.com/ndjson/ndjson-spec.git

### ISSUE THREAD

**Issue by Labqurzor-com** [ndjson/ndjson-spec#34]
https://github.com/
Markdown es una forma de aplicar estilo al texto en la web.

**Comment by Labqurzor-com** [comment]
https://github.com/ndjson/ndjson-spec/issues/34#issue-694053267

**Comment by Labqurzor-com** [comment]
[https://github.com/ndjson/ndjson-spec/issues/34#issue-694053267](https://github.com) `https://github.com/ndjson/ndjson-spec/issues/34#issue-694053267`

**Comment by contra** [comment]
@Labqurzor-com Please stop spamming this repo + other repos.
