### ISSUE TITLE
Such a weird specification...

### ISSUE THREAD

**Issue by vladimirdabic** [ndjson/ndjson-spec#40]
I have one very simple question, if you need to send/store multiple JSON objects, why not just put them in an array and send the array instead of this weird newline specification which doesn't really add anything new to JSON.

Your example:
```json
{"some":"thing"}
{"foo":17,"bar":false,"quux":true}
{"may":{"include":"nested","objects":["and","arrays"]}}
 ```

Why not just put it in an array (a valid JSON object) and send that?
```json
[
 {"some":"thing"},
 {"foo":17,"bar":false,"quux":true},
 {"may":{"include":"nested","objects":["and","arrays"]}}
]
```
... ?

**Comment by vladimirdabic** [comment]
When reading from a line stream you're literally just parsing each line as a JSON string. This specification is so unneeded, you can just store multiple objects in one array (which can be stored in one line as well).

**Comment by epugh** [comment]
so you can split things in half an process in parrallel..  by using the newline.   Though, I will say, I think it's odd we have ndjson, and jsonl: https://jsonlines.org/ !!!

**Comment by devingfx** [comment]
> finnp closed this as completed

🤣
